### ISSUE TITLE
[Protocol3] tests are failing on MacOS

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#412]
For example, when I ran `npm run test -- transpiled/test/testExchangeWithdrawalMode.js`, I got:

```bath
  2 passing (5m)
  7 failing

  1) Contract: Exchange
       Withdrawal Mode
         should go into withdrawal mode when a withdrawal request isn't processed:
     AssertionError: verifyBlock failed: ./blocks/block_3_1.json
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1306:7)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/loopring/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:3:12)
      at ExchangeTestUtil.verifyBlocks (transpiled/test/testExchangeUtil.js:776:16)
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1466:16)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/loopring/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:3:12)
      at ExchangeTestUtil.verifyPendingBlocks (transpiled/test/testExchangeUtil.js:865:16)
      at Suite.<anonymous> (test/testExchangeWithdrawalMode.ts:117:30)
      at Generator.next (<anonymous>)
      at fulfilled (transpiled/test/testExchangeWithdrawalMode.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  2) Contract: Exchange
       Withdrawal Mode
         should go into withdrawal mode when shutdown without reverting to initial state:
     AssertionError: verifyBlock failed: ./blocks/block_5_1.json
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1306:7)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/loopring/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:3:12)
      at ExchangeTestUtil.verifyBlocks (transpiled/test/testExchangeUtil.js:776:16)
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1466:16)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/loopring/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:3:12)
      at ExchangeTestUtil.verifyPendingBlocks (transpiled/test/testExchangeUtil.js:865:16)
      at Suite.<anonymous> (test/testExchangeWithdrawalMode.ts:180:30)
      at Generator.next (<anonymous>)
      at fulfilled (transpiled/test/testExchangeWithdrawalMode.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  3) Contract: Exchange
       Withdrawal Mode
         ERC20: withdraw from merkle tree:
     AssertionError: verifyBlock failed: ./blocks/block_6_1.json
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1306:7)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/loopring/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:3:12)
      at ExchangeTestUtil.verifyBlocks (transpiled/test/testExchangeUtil.js:776:16)
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1466:16)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/loopring/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:3:12)
      at ExchangeTestUtil.verifyPendingBlocks (transpiled/test/testExchangeUtil.js:865:16)
      at Suite.<anonymous> (test/testExchangeWithdrawalMode.ts:230:30)
      at Generator.next (<anonymous>)
      at fulfilled (transpiled/test/testExchangeWithdrawalMode.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  4) Contract: Exchange
       Withdrawal Mode
         ETH: withdraw from merkle tree:
     AssertionError: verifyBlock failed: ./blocks/block_7_1.json
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1306:7)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/loopring/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:3:12)
      at ExchangeTestUtil.verifyBlocks (transpiled/test/testExchangeUtil.js:776:16)
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1466:16)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/loopring/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:3:12)
      at ExchangeTestUtil.verifyPendingBlocks (transpiled/test/testExchangeUtil.js:865:16)
      at Suite.<anonymous> (test/testExchangeWithdrawalMode.ts:286:30)
      at Generator.next (<anonymous>)
      at fulfilled (transpiled/test/testExchangeWithdrawalMode.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  5) Contract: Exchange
       Withdrawal Mode
         Withdraw from merkle tree (protocol fee account):
     AssertionError: verifyBlock failed: ./blocks/block_8_2.json
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1306:7)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/loopring/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:3:12)
      at ExchangeTestUtil.verifyBlocks (transpiled/test/testExchangeUtil.js:776:16)
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1461:22)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/loopring/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:3:12)
      at ExchangeTestUtil.verifyPendingBlocks (transpiled/test/testExchangeUtil.js:865:16)
      at Suite.<anonymous> (test/testExchangeWithdrawalMode.ts:337:30)
      at Generator.next (<anonymous>)
      at fulfilled (transpiled/test/testExchangeWithdrawalMode.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  6) Contract: Exchange
       Withdrawal Mode
         Withdraw from deposit block:
     AssertionError: verifyBlock failed: ./blocks/block_9_1.json
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1306:7)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/loopring/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:3:12)
      at ExchangeTestUtil.verifyBlocks (transpiled/test/testExchangeUtil.js:776:16)
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1466:16)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/loopring/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:3:12)
      at ExchangeTestUtil.verifyPendingBlocks (transpiled/test/testExchangeUtil.js:865:16)
      at Suite.<anonymous> (test/testExchangeWithdrawalMode.ts:408:30)
      at Generator.next (<anonymous>)
      at fulfilled (transpiled/test/testExchangeWithdrawalMode.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  7) Contract: Exchange
       Withdrawal Mode
         Should not be able to do any more block state changes:
     AssertionError: verifyBlock failed: ./blocks/block_10_1.json
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1306:7)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/loopring/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:3:12)
      at ExchangeTestUtil.verifyBlocks (transpiled/test/testExchangeUtil.js:776:16)
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1466:16)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/loopring/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:3:12)
      at ExchangeTestUtil.verifyPendingBlocks (transpiled/test/testExchangeUtil.js:865:16)
      at Suite.<anonymous> (test/testExchangeWithdrawalMode.ts:508:30)
      at Generator.next (<anonymous>)
      at fulfilled (transpiled/test/testExchangeWithdrawalMode.js:4:58)
      at process._tickCallback (internal/process/next_tick.js:68:7)



npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! loopring_v3@3.0.0 test: `npm run transpile && node --max-old-space-size=4096 `which truffle` test --network development "transpiled/test/testExchangeWithdrawalMode.js"`
npm ERR! Exit status 7
npm ERR!
npm ERR! Failed at the loopring_v3@3.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/d/.npm/_logs/2019-08-12T12_56_16_473Z-debug.log
```

I tried this with both the release and the debug make mdoe. I also deleted *blocks* directory before running the test.

**Comment by dong77** [comment]
@Brechtpd can you verify on Linux all tests pass?

**Comment by Brechtpd** [comment]
I've let it run overnight and for me those tests pass, but the `testExchangeAdmin` tests fail in `before all` with `PROTOCOL_REGISTERED`. There's also a `reentrancy` test that fails with `clone` because it's `external` but not `reentrant` (but this is not dangerous so it doesn't matter).

The `blocks` directly doesn't need to be deleted, you probably need to delete the files in `keys` again.

**Comment by dong77** [comment]
> I've let it run overnight and for me those tests pass, but the `testExchangeAdmin` tests fail in `before all` with `PROTOCOL_REGISTERED`. There's also a `reentrancy` test that fails with `clone` because it's `external` but not `reentrant` (but this is not dangerous so it doesn't matter).
> 
> The `blocks` directly doesn't need to be deleted, you probably need to delete the files in `keys` again.

I'll try again ( some how I keep forgetting deleting `keys`) and also fix the testExchangeAdmin tests.

**Comment by dong77** [comment]
It turns out I have to resync up the circuit repository and re-make.
I made soem improvements for the package.json file in PR #415
