### ISSUE TITLE
[Protocol3] There are now many test failures

### ISSUE THREAD

**Issue by dong77** [Loopring/protocols#662]
10 failing
```

  1) Contract: Exchange
       Trade
         Unmatchable:
     AssertionError: validate_block failed: ./blocks/block_14_2.json
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1220:5)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:4:12)
      at ExchangeTestUtil.validateBlock (transpiled/test/testExchangeUtil.js:747:16)
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:2502:18)
      at Generator.next (<anonymous>)
      at fulfilled (transpiled/test/testExchangeUtil.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  2) Contract: Exchange
       Trade
         No funds available:
     AssertionError: validate_block failed: ./blocks/block_15_2.json
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1220:5)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:4:12)
      at ExchangeTestUtil.validateBlock (transpiled/test/testExchangeUtil.js:747:16)
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:2502:18)
      at Generator.next (<anonymous>)
      at fulfilled (transpiled/test/testExchangeUtil.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  3) Contract: Exchange
       Trade
         allOrNone (Buy, unsuccessful):
     AssertionError: validate_block failed: ./blocks/block_20_2.json
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1220:5)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:4:12)
      at ExchangeTestUtil.validateBlock (transpiled/test/testExchangeUtil.js:747:16)
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:2502:18)
      at Generator.next (<anonymous>)
      at fulfilled (transpiled/test/testExchangeUtil.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  4) Contract: Exchange
       Trade
         allOrNone (Sell, unsuccessful):
     AssertionError: validate_block failed: ./blocks/block_21_2.json
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1220:5)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:4:12)
      at ExchangeTestUtil.validateBlock (transpiled/test/testExchangeUtil.js:747:16)
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:2502:18)
      at Generator.next (<anonymous>)
      at fulfilled (transpiled/test/testExchangeUtil.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  5) Contract: Exchange
       Trade
         fillAmountB rounding error > 1%:
     AssertionError: validate_block failed: ./blocks/block_24_2.json
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1220:5)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:4:12)
      at ExchangeTestUtil.validateBlock (transpiled/test/testExchangeUtil.js:747:16)
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:2502:18)
      at Generator.next (<anonymous>)
      at fulfilled (transpiled/test/testExchangeUtil.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  6) Contract: Exchange
       Trade
         fillAmountB is 0 because of rounding error:
     AssertionError: validate_block failed: ./blocks/block_25_2.json
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1220:5)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:4:12)
      at ExchangeTestUtil.validateBlock (transpiled/test/testExchangeUtil.js:747:16)
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:2502:18)
      at Generator.next (<anonymous>)
      at fulfilled (transpiled/test/testExchangeUtil.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  7) Contract: Exchange
       Trade
         validUntil < now:
     AssertionError: validate_block failed: ./blocks/block_32_2.json
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1220:5)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:4:12)
      at ExchangeTestUtil.validateBlock (transpiled/test/testExchangeUtil.js:747:16)
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:2502:18)
      at Generator.next (<anonymous>)
      at fulfilled (transpiled/test/testExchangeUtil.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  8) Contract: Exchange
       Trade
         validSince > now:
     AssertionError: validate_block failed: ./blocks/block_33_2.json
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1220:5)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:4:12)
      at ExchangeTestUtil.validateBlock (transpiled/test/testExchangeUtil.js:747:16)
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:2502:18)
      at Generator.next (<anonymous>)
      at fulfilled (transpiled/test/testExchangeUtil.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  9) Contract: Exchange
       Trade
         Reused OrderID (tradeHistory.filled > order.amount):
     AssertionError: validate_block failed: ./blocks/block_36_2.json
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1220:5)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:4:12)
      at ExchangeTestUtil.validateBlock (transpiled/test/testExchangeUtil.js:747:16)
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:2502:18)
      at Generator.next (<anonymous>)
      at fulfilled (transpiled/test/testExchangeUtil.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)

  10) Contract: Exchange
       Trade
         Cancelled OrderID (order.orderID < tradeHistory.orderID):
     AssertionError: validate_block failed: ./blocks/block_38_2.json
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:1220:5)
      at Generator.next (<anonymous>)
      at /Users/d/Projects/protocols/packages/loopring_v3/transpiled/test/testExchangeUtil.js:8:71
      at new Promise (<anonymous>)
      at __awaiter (transpiled/test/testExchangeUtil.js:4:12)
      at ExchangeTestUtil.validateBlock (transpiled/test/testExchangeUtil.js:747:16)
      at ExchangeTestUtil.<anonymous> (test/testExchangeUtil.ts:2502:18)
      at Generator.next (<anonymous>)
      at fulfilled (transpiled/test/testExchangeUtil.js:5:58)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by dong77** [comment]
fixed
